In [19]:
import pandas as pd
import numpy as np
from  mlxtend.frequent_patterns import apriori,association_rules 
import seaborn as sns
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')
import time

In [2]:
df= pd.read_csv('OnlineRetail.csv',encoding = "ISO-8859-1")

In [3]:
df

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,01-12-2010 08:26,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,01-12-2010 08:26,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,01-12-2010 08:26,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,01-12-2010 08:26,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,01-12-2010 08:26,3.39,17850.0,United Kingdom
...,...,...,...,...,...,...,...,...
541904,581587,22613,PACK OF 20 SPACEBOY NAPKINS,12,09-12-2011 12:50,0.85,12680.0,France
541905,581587,22899,CHILDREN'S APRON DOLLY GIRL,6,09-12-2011 12:50,2.10,12680.0,France
541906,581587,23254,CHILDRENS CUTLERY DOLLY GIRL,4,09-12-2011 12:50,4.15,12680.0,France
541907,581587,23255,CHILDRENS CUTLERY CIRCUS PARADE,4,09-12-2011 12:50,4.15,12680.0,France
541908,581587,22138,BAKING SET 9 PIECE RETROSPOT,3,09-12-2011 12:50,4.95,12680.0,France

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 541909 entries, 0 to 541908
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   InvoiceNo    541909 non-null  object
 1   StockCode    541909 non-null  object
 2   Description  540455 non-null  object
 3   Quantity     541909 non-null  int64
 4   InvoiceDate  541909 non-null  object
 5   UnitPrice    541909 non-null  float64
 6   CustomerID   406829 non-null  float64
 7   Country      541909 non-null  object
dtypes: float64(2), int64(1), object(5)
memory usage: 33.1+ MB

In [5]:
df['Quantity'].value_counts()

 1        148227
 2         81829
 12        61063
 6         40868
 4         38484
           ...
-472           1
-161           1
-1206          1
-272           1
-80995         1
Name: Quantity, Length: 722, dtype: int64

In [6]:
df[df['Quantity']<0]

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
141,C536379,D,Discount,-1,01-12-2010 09:41,27.50,14527.0,United Kingdom
154,C536383,35004C,SET OF 3 COLOURED FLYING DUCKS,-1,01-12-2010 09:49,4.65,15311.0,United Kingdom
235,C536391,22556,PLASTERS IN TIN CIRCUS PARADE,-12,01-12-2010 10:24,1.65,17548.0,United Kingdom
236,C536391,21984,PACK OF 12 PINK PAISLEY TISSUES,-24,01-12-2010 10:24,0.29,17548.0,United Kingdom
237,C536391,21983,PACK OF 12 BLUE PAISLEY TISSUES,-24,01-12-2010 10:24,0.29,17548.0,United Kingdom
...,...,...,...,...,...,...,...,...
540449,C581490,23144,ZINC T-LIGHT HOLDER STARS SMALL,-11,09-12-2011 09:57,0.83,14397.0,United Kingdom
541541,C581499,M,Manual,-1,09-12-2011 10:28,224.69,15498.0,United Kingdom
541715,C581568,21258,VICTORIAN SEWING BOX LARGE,-5,09-12-2011 11:57,10.95,15311.0,United Kingdom
541716,C581569,84978,HANGING HEART JAR T-LIGHT HOLDER,-1,09-12-2011 11:58,1.25,17315.0,United Kingdom
541717,C581569,20979,36 PENCILS TUBE RED RETROSPOT,-5,09-12-2011 11:58,1.25,17315.0,United Kingdom

In [7]:
df[df['Quantity']<0]=np.nan

In [8]:
df.isnull().mean()*100

InvoiceNo       1.960477
StockCode       1.960477
Description     2.069720
Quantity        1.960477
InvoiceDate     1.960477
UnitPrice       1.960477
CustomerID     26.569959
Country         1.960477
dtype: float64

In [9]:
df.dropna(inplace=True)

In [10]:
df.duplicated().sum()

5192

In [11]:
df=df.drop_duplicates()

In [12]:
df.isnull().mean()*100

InvoiceNo      0.0
StockCode      0.0
Description    0.0
Quantity       0.0
InvoiceDate    0.0
UnitPrice      0.0
CustomerID     0.0
Country        0.0
dtype: float64

In [13]:
df['Country'].value_counts()

United Kingdom          349227
Germany                   9027
France                    8327
EIRE                      7228
Spain                     2480
Netherlands               2363
Belgium                   2031
Switzerland               1842
Portugal                  1453
Australia                 1184
Norway                    1072
Italy                      758
Channel Islands            747
Finland                    685
Cyprus                     603
Sweden                     450
Austria                    398
Denmark                    380
Poland                     330
Japan                      321
Israel                     245
Unspecified                241
Singapore                  222
Iceland                    182
USA                        179
Canada                     151
Greece                     145
Malta                      112
United Arab Emirates        68
European Community          60
RSA                         58
Lebanon                     45
Lithuania                   35
Brazil                      32
Czech Republic              25
Bahrain                     17
Saudi Arabia                 9
Name: Country, dtype: int64

In [14]:
df['Description'] = df['Description'].str.strip()
df['InvoiceNo'] = df['InvoiceNo'].astype('str')  
df1=df[~df['InvoiceNo'].str.contains('c')]

In [15]:
countries=df['Country'].unique().tolist()

In [16]:
countries

['United Kingdom',
 'France',
 'Australia',
 'Netherlands',
 'Germany',
 'Norway',
 'EIRE',
 'Switzerland',
 'Spain',
 'Poland',
 'Portugal',
 'Italy',
 'Belgium',
 'Lithuania',
 'Japan',
 'Iceland',
 'Channel Islands',
 'Denmark',
 'Cyprus',
 'Sweden',
 'Finland',
 'Austria',
 'Greece',
 'Singapore',
 'Lebanon',
 'United Arab Emirates',
 'Israel',
 'Saudi Arabia',
 'Czech Republic',
 'Canada',
 'Unspecified',
 'Brazil',
 'USA',
 'European Community',
 'Bahrain',
 'Malta',
 'RSA']

In [ ]:
for i,country in enumerate(countries):
             basket= df[df['Country'] ==countries[i]].groupby(['InvoiceNo', 'Description'])['Quantity'].sum().unstack().reset_index().fillna(0).set_index('InvoiceNo')
            #***********************
             def hot_encode1(P):  
                if(P<= 0):  
                    return 0  
                if(P>= 1):  
                    return 1
             basket1_encoded = basket.applymap(hot_encode1)  
             basket = basket1_encoded 
             frq_items1 = apriori(basket, min_support = 0.05, use_colnames = True)  
             rules1 = association_rules(frq_items1, metric ="lift", min_threshold = 1)  
             rules1 = rules1.sort_values(['confidence', 'lift'], ascending =[False, False]) 
             print('For :     '+countries[i])
             print(rules1.head())
             print("**********************************************************************************************************")
             time.sleep(60)

For :     United Kingdom
Empty DataFrame
Columns: [antecedents, consequents, antecedent support, consequent support, support, confidence, lift, leverage, conviction, zhangs_metric]
Index: []
**********************************************************************************************************
For :     France
                                           antecedents  \
44                        (JUMBO BAG WOODLAND ANIMALS)
258  (RED TOADSTOOL LED NIGHT LIGHT, PLASTERS IN TI...
270  (RED TOADSTOOL LED NIGHT LIGHT, PLASTERS IN TI...
300  (SET/6 RED SPOTTY PAPER CUPS, SET/20 RED RETRO...
299  (SET/6 RED SPOTTY PAPER PLATES, SET/20 RED RET...

                         consequents  antecedent support  consequent support  \
44                         (POSTAGE)            0.077121            0.771208
258                        (POSTAGE)            0.051414            0.771208
270                        (POSTAGE)            0.053985            0.771208
300  (SET/6 RED SPOTTY PAPER PLATES)            0.102828            0.128535
299    (SET/6 RED SPOTTY PAPER CUPS)            0.102828            0.138817

      support  confidence      lift  leverage  conviction  zhangs_metric
44   0.077121       1.000  1.296667  0.017645         inf       0.247911
258  0.051414       1.000  1.296667  0.011763         inf       0.241192
270  0.053985       1.000  1.296667  0.012351         inf       0.241848
300  0.100257       0.975  7.585500  0.087040   34.858612       0.967673
299  0.100257       0.975  7.023611  0.085983   34.447301       0.955918
**********************************************************************************************************